### PR TITLE
Geo edits

### PR DESCRIPTION
**Pull request by gitriley**
Additions
- Added the cursor drag and drop feature 
- Some css formatting of the data-detail panel
- Template now displays lat and long of the selected marker

bug to work out:
- When dropping the marker, the location does not get set until the map itself is clicked. Clicking on and detaching from the svg cursor does not set the marker location. These two events should be a single event.

### CODE REVIEW

**Comment by vanwars** [comment]
Wow, Riley! Works great and looks great! I made a few changes:

1. Added code so that the geo-reference click triggered the "placeMarkerOnMapXY" method in basemap.js.
2. Renamed "long" (potentially a reserved word) to "lng."

Some requests: 
1. Can you keep experimenting w/the formatting and positioning of the lat / lng output (perhaps less whitespace)? And maybe move the actual lat / lng output underneath the button if it exists (and don't output it at all otherwise).
2. Can you add similar functionality to the photo and audio forms?
3. Can you make the "cursor icon" look like the highlighted version of the marker (as opposed to the regular version)?

**Comment by gitriley** [comment]
Great, yes, I'll work on the above tasks a bit today and tomorrow.
This new git system is great, by the way. It's super helpful to be able to see the changes to the code so readily.

**Comment by gitriley** [comment]
- fixed carousel so photos don't get cropped
- added pin-placing buttons to audio and photo html templates
- added overlay (css filter, actually) to indicate that the photo is in the process of rotating (this step may still need some work . I held off on the spinning cog because it was buggy)

**Comment by vanwars** [comment]
Thanks Riley, Lots of progress. I just did some testing, and have some requests:

1. Geo-referencing: 
    * lat / lng are flipped (index 0 --> lng, index 1 --> lat), and can you display the coords less prominently (similar to the way they're displayed in the Gallery View for the "photo" data type). And don't display anything if they're undefined.
   * Ensure coords are displayed for all data types consistently
   * For each of the data types, can the button say "ADD LOCATION" and "REMOVE LOCATION"?
   * When the "ADD LOCATION" mode is active, can you make it so the button changes slightly (background-color probably) until the geo-referencing is complete, and add a message underneath that says "click on the map to add location"?

2. Carousel positioning: looks good for some photos, and for others, it's breaking. I can show you when I see you.

3. Photo rotation: great start. Needs a bit more feedback and formatting, but you're on the right track.

**Comment by gitriley** [comment]
Hey Sarah, will you review this pr? There are a lot of css changes. They should cover all the css modifications we were looking for, hopefully free of conflicts

**Comment by vanwars** [comment]
Overall comments: Riley, this looks great! The photo rotation feedback is excellent, and the geo-referencing + changing buttons + messaging + icon changes are great. In addition to my inline comments, I did some testing on the carousel with different #s of audio and photos on the three different screens (map, spreadsheet, gallery). A few very minor visual bugs (but functionality is good):

1. When there's only a single photo for the carousel:
   1. the caption sometimes overlaps with the properties box<br>screen shot 2017-03-09 at 4 17 24 pm
   2. for landscape photos, there's too much spacing between the title and the photo, and the photo sometimes runs off the screen on the right-hand side:<br>screen shot 2017-03-09 at 4 17 39 pm

I think a simple fix would be, if it's a single photo, to just have a plain image render underneath the title with a caption (versus the view-photo and photo-container additions).

2. Audio carousel covers up the properties box:<br>
screen shot 2017-03-09 at 4 19 25 pm

3. In gallery view, lat / lng not centered. I'm not sure it's necessary to show lat / lng in gallery view. What do you think?
screen shot 2017-03-09 at 4 19 56 pm

4. In spreadsheet view, the carousel has a gray box and a white box behind it. Can you make it so that it's just black?
screen shot 2017-03-09 at 4 21 02 pm

**Comment by vanwars** [comment]
Hey Riley,

Just checking in on the status of this branch. Kathryn was hoping to do some geo-referencing w/kids tomorrow, if possible, but I think there are still a few outstanding bugs on this branch? Let me know if this is something you could get to today -- if not, no problem. We'll figure something out.

--S

**Pull request merged**
