### PR TITLE
Modifying sharing serializer so username is exposed

### PR DESCRIPTION
**Pull request by vanwars**
Makes the UI simpler.

### CODE REVIEW

**Comment by vanwars** [comment]
Hi Tap,
I made a change to the sharing endpoint to simplify the UI. Now, when Keshav implements sharing, he just has to post the username (plain text) and authority id (1, 2, or 3) instead of user id (which would require an extra user lookup request to API). Can you give it a quick look?

**Comment by tap2k** [comment]
Should a user be able to change an assigned permission via a new POST command? Currently that doesnt work.

**Comment by tap2k** [comment]
Also, should we allow assigning permissions to the owner of the project? Currently you can - and its very helpful for testing :-)

**Comment by vanwars** [comment]
> Should a user be able to change an assigned permission via a new POST command? Currently that doesnt work.

I don't think so. Updates should happen in the PUT /api/0/projects/2/{{id}}/{{username}}/ to follow REST conventions (updating an _existing_ resource).

> Also, should we allow assigning permissions to the owner of the project? Currently you can - and its very helpful for testing :-)

Good point. It doesn't really make sense to allow this, but I don't think it hurts anything. Should I add this check?

**Comment by tap2k** [comment]
Lets leave it as is... Def helps for testing purposes - and doesnt hurt like u say

**Pull request merged**
