### PR TITLE
Celery

### PR DESCRIPTION
**Pull request by awesomescot**
Basic processing moved to celery.

Use this command to run the worker process from the apps directory:
celery -A tasks worker -l info

### CODE REVIEW

**Comment by vanwars** [comment]
Amazing! It worked. Some questions:
* Do you have any thoughts regarding how we might write a test or something to check that celery is running? One of the issues we've consistently run into in the past is having the cronjob go down and us not know about it. Any ideas?
* A related question: how can we get this "celery -A tasks worker -l info" to always be running?
* In the event that I want to re-process the map for some reason, can you update the ScanSerializerUpdate so that when the user resets the status to "ready for processing," it triggers the celery task again? You'll have to override the ```def update(self, instance, validated_data)``` method of the ScanSerializerUpdate class (in barcoded_serialized.py). To do this, take a look at:
/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py, line 800.
* What happens when lots of maps are uploaded at once? Is there an admin interface to view which maps are actively being processed and which are queued?

Thanks! Great work!!

**Comment by awesomescot** [comment]
Hmm.  So there are many monitoring softwares out there but I would say at this point it might be overkill to deploy a full monitoring framework.  I'll look around a little bit for a simple one, another option would be to have our webapp monitor it, and send us an email.  Basically all we need to do is monitor the length of the queue in rabbit, which should be easy to do, it's just a matter of what should be running that code and not cause us more headache.  Here is some stuff they suggest:  http://docs.celeryproject.org/en/latest/userguide/monitoring.html

- there are things called process monitors which will restart a process if it ever stops.  I think there is configuration for many of these, I've used runit in the past, but I'm sure they are all similar.
- I'll look into the update case.
- From here,http://docs.celeryproject.org/en/latest/userguide/monitoring.html, there is this thing called flower which looks kind of like an admin interface.  We could try that out.

If you're interested in more reading here's someone else talking about running it in prod:  https://www.caktusgroup.com/blog/2014/09/29/celery-production/

**Comment by vanwars** [comment]
Flow-er looks great! Please install it and give it a try. I'm hoping that it's simple, and it will be great to be able to control celery settings from a web UI! Thanks for the reading.

**Comment by awesomescot** [comment]
flower was super easy to install and run.  Just 'pip install flower' and 'cd /localground/apps/; celery -A tasks flower'.  So we can definitely install that in dev.  I guess the only question is how to secure it, I guess we can use basic auth for that.

**Pull request merged**
