### PR TITLE
Upload

### PR DESCRIPTION
**Pull request by zmmachar**
Adding upload modal to new map editor/couple style changes to infobubbles

### CODE REVIEW

**Comment by vanwars** [comment]
Hi Zack,
Looking good. Here is what I tested:

1. Upload via iFrame
The upload worked (tested for photos and audio), and when I closed the iFrame, the data refreshed with the new photos added. Nice. A few bells-and-whistles requests:
 * Is there a way to signal to the user which photos are the new ones in the updated right-hand panel listing? Perhaps a temporary “new” label or highlight that fades over time? Up to you.
 * Sizing…popup is too big for my screen and it shows a weird iframe border. Screenshot attached. Can you mess w/the CSS / JS to make this more visually appealing?
 * Refreshing all of the data for all of the projects might be expensive for larger projects. OK for now, but just flagging this for the future (unless you can think of a quick workaround to only pull down the new photo / audio files.

2. Editable InfoBubbles
The editable infobubbles look nice. For the edit-mode version audio infobubble, could you also add a play / stop button?

3. I tested the rotate right / left buttons of the edit-mode version photo infobubble. The server caching may be making it so that it doesn't work, or something else might be going on. Not sure if you wanted me to test photo rotation in this PR, but I saw some code for it, so I wanted to let you know.

4. Can you write some Jasmine tests, just so we can both get back in the habit of doing it (and I will do the same for my PRs)? Even some basic ones like:
   * upload_button_opens_infowindow
   * close_button_refreshes collections
   * edit_version_of_photo_infobubble_has_image

**Comment by zmmachar** [comment]
Should be good for review.  Thanks for the rotation fixes!

**Comment by vanwars** [comment]
#### Done (successfully tested):
* Edit audio has play / stop button.
* Rotation is working
* Formatting (though I made a few final edits to the CSS for the upload iframe b/c it was looking weird on my computer's screen).
* Jasmine tests

#### Skipping for now?
* user feedback re: which photos are new on refresh.

#### One more bug
* If I have 2 or more projects turned on in the map editor and I click the "upload" button, the iFrame doesn't select the active project (the one with the dark blue border around it). Can you make it so that the default project in the iFrame is coordinated with the active project in the map editor? You can detect it via: appUtilities.getActiveProjectID().

**Comment by zmmachar** [comment]
Upload modal should now default to active project id correctly

**Pull request merged**
