### PR TITLE
Export KML

### PR DESCRIPTION
**Pull request by stlim0730**
This branch includes REST API renderer that exports projects, photos, audio, and markers in KML.

### CODE REVIEW

**Comment by tap2k** [comment]
Hi Taek - This looks great! Can you add a test for this? Thanks!

**Comment by stlim0730** [comment]
I saw an existing test function for GeoJson. It seemed to check if the output has the same geometry attributes as the input. For consistency with the existing test, I put that code to test a list of media instances has the correct geometry attributes.

**Comment by tap2k** [comment]
But to do that you would actually have to pull the data from KML and test the actual coordinates, right? Im just a bit unsure of what that code is currently testing.

**Comment by stlim0730** [comment]
The code actually does that; `data = response.content` has a KML string rendered with the arbitrary geometric attributes. `point_template` properly formats the geometric attributes for the sanity check.

**Comment by tap2k** [comment]
Where in the code do you actually do something with that data variable? The only tests I see in the code are that the XML is valid, and then the following, which as far as I can tell tests the truth value of a string?

`self.assertTrue(point_template.format(p['coordinates'][0], p['coordinates'][1]))`

**Comment by stlim0730** [comment]
Oh, now I get your point.
What I wanted to do is `self.assertTrue(point_template.format(p['coordinates'][0], p['coordinates'][1]) in data)`. Such a stupid mistake :(
Let me make the commit with the correction.

**Pull request merged**
