### PR TITLE
Map Image UI Wired Up + Scan Renamed to MapImage

### PR DESCRIPTION
**Pull request by vanwars**

### CODE REVIEW

**Comment by vanwars** [comment]
This PR is ready to be tested. Summary of Updates:

* I renamed the model "Scan" to MapImage for consistency
* I wrote a lot of new tests, both Django & JavaScript tests
* Map overlays should now be working in the UI

To test:
* Make sure server-side Django tests are passing
* Make sure client-side Jasmine tests are passing by clicking this [link](http://localhost:7777/static/backbone/js/test/index.html) (locally). All dots should be green.
* Go through a manual testing process where you:
   1. print a map
   2. annotate and upload it as a map image
   3. process it (should run automatically if you rebuild vagrant box from scratch (don't forget the Sendmail API key).
   4. make sure it’s viewable in the map editor (overlaid in the right place)

**Comment by tap2k** [comment]
Getting the following Jasmine error:
Error: Expected spy trigger to have been called with [ 'change-center', { lat: Function, lng: Function } ] but actual calls were [ 'map-ready' ], [ 'change-center', { lat: Function, lng: Function } ], [ 'change-zoom', 18 ], [ 'set-map-type', 12 ].
    at stack (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1441:17)
    at buildExpectationResult (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1411:14)
    at Spec.Env.expectationResultFactory (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:533:18)
    at Spec.addExpectationResult (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:293:34)
    at Expectation.addExpectationResult (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:477:21)
    at Expectation.toHaveBeenCalledWith (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1365:12)
    at Object.<anonymous> (http://daya.ischool.berkeley.edu:7777/static/backbone/js/test/spec/snapshot-loader-test.js?bust=1462560974667:46:47)
    at attemptSync (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1759:24)
    at QueueRunner.run (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1747:9)
    at QueueRunner.execute (http://daya.ischool.berkeley.edu:7777/static/backbone/js/external/jasmine-2.1.3/jasmine.js?bust=1462560974667:1733:10)

**Comment by vanwars** [comment]
Hi Tap,

That's the error from the old tests. Please refresh your browser a few times and make sure that your current branch is image-overlays. There should be 276 specs that run.

**Comment by vanwars** [comment]
Hmmm. Yeah, I just checked http://daya.ischool.berkeley.edu:7777 and I think you're on the wrong branch (only 198 tests are running).

**Comment by tap2k** [comment]
yes messing up the git commands. didnt do a pull...

**Comment by tap2k** [comment]
Now Im getting the following error in the server-side tests after a fresh vagrant install:

ImportError: No module named hmac.urls

**Comment by tap2k** [comment]
OK found that prior issue

**Comment by tap2k** [comment]
All works great.  In the future, cab we improve the scanned map PDF layout so that the map part can be bigger?

**Comment by vanwars** [comment]
Deployed to dev. Re: print PDF improvements, can you make a bug describing what enhancements you want?

**Pull request merged**
