### PR TITLE
adding name for password reset

### PR DESCRIPTION
**Pull request by awesomescot**

### CODE REVIEW

**Comment by vanwars** [comment]
I'm not receiving an email, but it could be a vagrant issue. I'm going to try and deploy this onto the dev server and see if I get an email....

**Comment by vanwars** [comment]
OK. I tested on dev.localground.org and I did receive an email. So that's fixed. Thanks! But, when I click the password reset link (in the email), there's a new error (pasted below). Currently dev.localground.org is pointing to the password-reset branch, so you can test this for yourself also. Can you take a look?

screen shot 2016-02-28 at 10 37 09 am

**Comment by awesomescot** [comment]
The issue about has been fixed.  And I added sendgrid in so that I could test locally.

**Comment by vanwars** [comment]
Hi Scot, 

I tested, and the emailer does work when I try to register for a new account. However, when I try to reset my password, enter my email into the textbox, and submit, I do get the confirmation message: "An email with password reset instructions has been sent."

However, no email ever arrives. Is this working for you locally?

**Comment by vanwars** [comment]
newer PR addresses this PR.

**Pull request closed without merging**
